media:
  input: site/assets/media
  output: /assets/media
  rename: safe

settings:
  commit:
    identity: user
    templates:
      update: "catalog: update literature"

content:
  - name: literature
    label: Speech Front-End 研究地图
    type: file
    path: data/literature.csv
    format: datagrid
    operations:
      delete: false
